In [1]:
import pickle
import numpy as np
with open('results/scores_eqodds_rf_s33_itr10_.pkl', "rb") as fb:
    pkl_test = pickle.load(fb)
print(np.array(pkl_test).shape)

(10, 7500, 1)


In [2]:
print(pkl_test[0])
print(len(pkl_test[0]))

[[0.61077943]
 [0.20116416]
 [0.51200242]
 ...
 [0.2883068 ]
 [0.40429118]
 [0.60821022]]
7500


In [3]:
with open('results/scores_roc_rf_s33_itr10_eo.pkl', "rb") as fb:
    pkl_test = pickle.load(fb)
for key in pkl_test.keys():
    print(np.array(pkl_test[key]).shape)

(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)


In [4]:
with open('results/scores_reduction_rf_s33_itr10_eo.pkl', "rb") as fb:
    pkl_test = pickle.load(fb)
for key in pkl_test.keys():
    print(np.array(pkl_test[key]).shape)

(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)
(10, 7500, 1)


In [5]:
print(pkl_test.keys())

dict_keys([0.1, 1, 4, 6, 8, 9, 10, 12])


In [6]:
with open('results/scores_leveraging_rf_s33_itr10_eo.pkl', "rb") as fb:
    pkl_test = pickle.load(fb)
print(np.array(pkl_test).shape)


(10, 7500, 1)


In [7]:
print(pkl_test[0])

[[1.]
 [0.]
 [1.]
 ...
 [0.]
 [0.]
 [1.]]


In [8]:
with open('results/scores_original_rf_s33_itr10_.pkl', "rb") as fb:
    pkl_test = pickle.load(fb)
print(np.array(pkl_test).shape)

(10, 7500, 1)


In [9]:
print(pkl_test[0])

[[0.6332629 ]
 [0.11957689]
 [0.69633598]
 ...
 [0.28910358]
 [0.46879998]
 [0.63118093]]


## Validation files

In [10]:
import pickle
import numpy as np
with open('results/valid_scores_eqodds_rf_s33_itr10_.pkl', "rb") as fb:
    pkl_test = pickle.load(fb)
print(np.array(pkl_test).shape)

(10, 7500, 1)


In [12]:
print(pkl_test[0])

[[0.68205972]
 [0.45313406]
 [0.29110837]
 ...
 [0.34280013]
 [0.77969397]
 [0.7892821 ]]


In [13]:
import pickle
import numpy as np
with open('results/valid_scores_original_rf_s33_itr10_.pkl', "rb") as fb:
    pkl_test = pickle.load(fb)
print(np.array(pkl_test).shape)

(10, 7500, 1)


In [14]:
print(pkl_test[0])

[[0.64024338]
 [0.50571253]
 [0.31047436]
 ...
 [0.29576181]
 [0.70169933]
 [0.68993724]]


In [47]:
with open('results/valid_scores_leveraging_rf_s0_itr1_eo.pkl', "rb") as fb:
    pkl_test = pickle.load(fb)
print(np.array(pkl_test).shape)

(1, 2176, 1)


In [51]:
with open('results/valid_scores_roc_rf_s0_itr1_eo.pkl', "rb") as fb:
    pkl_test = pickle.load(fb)
for key in pkl_test.keys():
    print(np.array(pkl_test[key]).shape)

(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)


In [52]:
with open('results/valid_scores_reduction_rf_s0_itr1_eo.pkl', "rb") as fb:
    pkl_test = pickle.load(fb)
for key in pkl_test.keys():
    print(np.array(pkl_test[key]).shape)

(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)
(1, 2176, 1)


In [53]:
print(pkl_test[0.001][0])

[[0.38411569]
 [0.        ]
 [1.        ]
 ...
 [0.        ]
 [0.38411569]
 [1.        ]]


In [54]:
with open('results/valid_scores_mp_rf_s42_itr3_eo.pkl', "rb") as fb:
    pkl_test = pickle.load(fb)
print(np.array(pkl_test).shape)

(3,)


In [57]:
for key in pkl_test[0].keys():
    print(np.array(pkl_test[0][key]))

[0.39531112 0.14224639 0.83521051 ... 0.09254482 0.39404822 0.93200743]
[0.39588149 0.14263215 0.83534686 ... 0.09206994 0.39311419 0.93204966]
[0.39800567 0.14408617 0.83583682 ... 0.09035255 0.38970562 0.93219836]
